name: PuebloHG
version: ${project.version}
main: me.putindeer.puebloHG.Main
api-version: '1.21'
author: putindeer
description: Hunger Games Plugin
website: github.com/putindeer
softdepend:
  - PlaceholderAPI

commands:
  start:
    description: Inicia una partida de Hunger Games
    permission: hg.admin
  restock:
    description: Rellena los cofres del Hunger Games
    permission: hg.admin
  forceend:
    description: Fuerza el final de la partida
    permission: hg.admin
  registerchests:
    description: Guarda los cofres del mapa
    permission: hg.admin
  leaderboard:
    description: Muestra el top 5 del tablero de puntos del evento
    aliases:
      - lb
      - toppoints
  fullleaderboard:
    description: Muestra el top completo del tablero de puntos del evento
    aliases:
      - fulllb
      - fulltoppoints